1. Installing TensorFlow
Before we start, we need to install TensorFlow. You can install TensorFlow using pip.

In [ ]:
!pip install --upgrade tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.3/615.3 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 91.0 MB/s eta 0:00:00
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.17.1
    Uninstalling tensorboard-2.17.1:
      Successfully uninstalled tensorboard-2.17.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.17.1
    Uninstalling tensorflow-2.17.1:
      Successfully uninstalled tensorflow-2.17.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.18.0 which is incompatible.


2. TensorFlow Basics
Tensors
Tensors are the fundamental building blocks of TensorFlow. They are multi-dimensional arrays with a uniform type (called a dtype).

In [ ]:
import tensorflow as tf

# Creating a constant tensor
print(tf.__version__)

tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)

# Basic operations
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

add = tf.add(a, b)
print(add)

multiply = tf.multiply(a, b)
print(multiply)

2.18.0
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


3. Building a Simple Neural Network
Loading Data
For this tutorial, we will use the MNIST dataset, which contains images of handwritten digits.

In [ ]:
from tensorflow.keras.datasets import mnist

# Load data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the images to [0, 1] range
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Defining the Model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Define the model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

Compiling the Model
Next, we compile the model by specifying the optimizer, loss function, and metrics.

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Training the Model
Now we can train the model using the training data.

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8772 - loss: 0.4331
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9637 - loss: 0.1235
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9765 - loss: 0.0769
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9828 - loss: 0.0576
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9862 - loss: 0.0455


Evaluating the Model
Finally, we evaluate the model on the test data.

In [ ]:
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print('\nTest accuracy:', test_acc)


313/313 - 1s - 2ms/step - accuracy: 0.9784 - loss: 0.0730

Test accuracy: 0.9783999919891357


Saving and Loading Models
Saving a Model
You can save the entire model or just the weights.

In [ ]:
# Save the entire model
model.save('my_model.keras')

# Save only the weights
model.save_weights('my_model_weights.weights.h5')

Loading a Model

In [ ]:
# Load the entire model
loaded_model = tf.keras.models.load_model('my_model.keras')

# Load the weights into a new model
new_model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])
new_model.load_weights('my_model_weights.weights.h5')


/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_lib.py:713: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 6 variables whereas the saved optimizer has 10 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


Mathematical Foundations of TensorFlow
Scalers

In [ ]:
import tensorflow as tf

# Creating a scalar
scalar = tf.constant(5)
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


Vectors

In [ ]:
vector = tf.constant([1, 2, 3, 4])
print(vector)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


Matrices

In [ ]:
# Creating a matrix
matrix = tf.constant([[1, 2], [3, 4]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Tensors

In [ ]:
# Creating a 3-dimensional tensor
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


Tensor Operations
Basic Operations

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Element-wise addition
add = tf.add(a, b)
print(add)

# Element-wise multiplication
multiply = tf.multiply(a, b)
print(multiply)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


Broadcasting

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([[1], [2], [3]])

# Broadcasting a to match the shape of b
broadcast_add = tf.add(a, b)
print(broadcast_add)

tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


Linear Algebra in TensorFlow
Matrix Multiplication:

In [ ]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
matmul = tf.matmul(a, b)
print(matmul)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


Linear Algebra in TensorFlow
Matrix Inversion and Transposition:

In [ ]:
# Matrix transposition
transpose = tf.transpose(a)
print(transpose)

# Matrix inversion
inverse = tf.linalg.inv(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
print(inverse)

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


Gradient ComputationGradient Computation

In [ ]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2

# Compute the gradient of y with respect to x
gradient = tape.gradient(y, x)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


Eigenvalues and Eigenvectors

In [ ]:
matrix = tf.constant([[2.0, 1.0], [1.0, 2.0]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eigh(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: tf.Tensor([0.99999994 2.9999998 ], shape=(2,), dtype=float32)
Eigenvectors: tf.Tensor(
[[-0.70710677  0.70710677]
 [ 0.70710677  0.70710677]], shape=(2, 2), dtype=float32)
